In [67]:
import numpy as np
import pandas as pad
import seaborn as sns
import matplotlib as plt
from sklearn.datasets import load_iris
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

Code for Linear SVM

In [149]:
class LinearSvm:
    def __init__(self,c=1,alpha=0.01,epochs=1000):
        self.c=c
        self.alpha=alpha
        self.epochs=epochs
        
    def fit(self,x,y):
        self.w= np.zeros(x.shape[1])
        self.b=0

        for epoch in range(self.epochs):
            for i in range(len(x)):
                condition= y[i]*(np.dot(x[i],self.w)+self.b)
                if condition >= 1:
                    self.w=self.w- self.alpha*self.w
                else:
                    self.w=self.w-self.alpha*(self.w-self.c*y[i]*x[i])
                    self.b=self.b-self.alpha*(-self.c*y[i])
            print(self.w)
            print(self.b)
                    
    def decision_function(self,x):
        return np.dot(x, self.w) + self.b

    def predict(self, x):
        return np.sign(self.decision_function(x))

Code for One vs Rest

In [150]:
class OneVsRestSVM:
    def __init__(self, c=1.0, alpha=0.001, epochs=1000):
        self.c = c
        self.alpha = alpha
        self.epochs = epochs
        self.models = {}

    def fit(self, x, y):
        self.classes = np.unique(y)
        for cls in self.classes:
            enc=np.where(y==cls,1,-1)
            model=LinearSvm(c=self.c,alpha=self.alpha,epochs=self.epochs)
            model.fit(x,enc)
            self.models[cls]=model
            
    def predict(self, X):
        scores = np.array([model.decision_function(X) for model in self.models.values()])
        return np.argmax(scores, axis=0)

In [151]:
iris=load_iris()

In [152]:
x=iris.data

In [153]:
y=iris.target

In [154]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [155]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [156]:
from sklearn.preprocessing import StandardScaler

In [157]:
scaler=StandardScaler()
x=scaler.fit_transform(x)

In [158]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [159]:
svm = OneVsRestSVM(c=1.0, alpha=0.001, epochs=1000)

In [160]:
svm.fit(x_train,y_train)

[-0.0731536   0.06704738 -0.0967401  -0.09222599]
-0.04000000000000003
[-0.13803113  0.12650951 -0.18253573 -0.1740182 ]
-0.08000000000000006
[-0.1862846   0.1775103  -0.25190131 -0.24135876]
-0.11500000000000009
[-0.21085263  0.20801741 -0.29202033 -0.280231  ]
-0.1550000000000001
[-0.21601328  0.22559266 -0.30849739 -0.29548228]
-0.19800000000000015
[-0.21722438  0.23694192 -0.31702426 -0.30184629]
-0.23600000000000018
[-0.21829571  0.24575386 -0.3233577  -0.3055124 ]
-0.2670000000000002
[-0.21952907  0.25154811 -0.32871525 -0.30955398]
-0.2950000000000002
[-0.22097044  0.25697948 -0.33302583 -0.31223341]
-0.3170000000000002
[-0.22239237  0.2620375  -0.33650842 -0.31447729]
-0.33600000000000024
[-0.2232517   0.26725654 -0.33872947 -0.31512053]
-0.35400000000000026
[-0.22380745  0.27076252 -0.33936664 -0.3142874 ]
-0.3700000000000003
[-0.22579393  0.27450874 -0.34206101 -0.31572587]
-0.3830000000000003
[-0.22785193  0.27822071 -0.34505573 -0.31778381]
-0.3940000000000003
[-0.2296771  

In [161]:
y_pred = svm.predict(x_test)
accuracy = np.mean(y_pred == y_test)

In [162]:
accuracy

0.7

In [163]:
print("Predicted labels:", y_pred)
print("True labels     :", y_test)
print(f"Test Accuracy: {accuracy:.4f}")

Predicted labels: [2 0 2 2 2 0 0 2 2 2 2 0 0 0 0 2 2 2 2 2 0 2 0 2 2 2 2 2 0 0]
True labels     : [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
Test Accuracy: 0.7000
